//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace HrGrains
{
    using System;
    using HrGrainInterfaces;
    using Orleans;
    using Orleans.Runtime;
    using Orleans.CodeGeneration;
    using System.Runtime.InteropServices;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    using System.Collections;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("HrGrains.HrGrains.Employee")]
    public class EmployeeState : global::Orleans.CodeGeneration.GrainState, IEmployeeState
    {
        

            public Int32 @Level { get; set; }

            public IManager @Manager { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("Level", out value)) @Level = value is Int64 ? (Int32)(Int64)value : (Int32)value;
                if (values.TryGetValue("Manager", out value)) @Manager = (IManager) value;
            }

            public override System.String ToString()
            {
                return System.String.Format("EmployeeState( Level={0} Manager={1} )", @Level, @Manager);
            }
        
        public EmployeeState() : 
                base("HrGrains.Employee")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["Level"] = this.Level;
            result["Manager"] = this.Manager;
            return result;
        }
        
        private void InitStateFields()
        {
            this.Level = default(Int32);
            this.Manager = default(IManager);
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            EmployeeState input = ((EmployeeState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            EmployeeState input = ((EmployeeState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            EmployeeState result = new EmployeeState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("HrGrains.HrGrains.Manager")]
    public class ManagerState : global::Orleans.CodeGeneration.GrainState, IManagerState
    {
        

            public List<IEmployee> @Reports { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("Reports", out value)) @Reports = (List<IEmployee>) value;
            }

            public override System.String ToString()
            {
                return System.String.Format("ManagerState( Reports={0} )", @Reports);
            }
        
        public ManagerState() : 
                base("HrGrains.Manager")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["Reports"] = this.Reports;
            return result;
        }
        
        private void InitStateFields()
        {
            this.Reports = new List<IEmployee>();
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            ManagerState input = ((ManagerState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            ManagerState input = ((ManagerState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            ManagerState result = new ManagerState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
